# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: "Florian von Behr"
subtitle: "CG Supervisor • Technical Director • Pipeline Engineer"

email: "florian@florianvonbehr.de"

description: >- # this means to ignore newlines until "baseurl:"
  Building scalable CGI pipelines for high-end visualization.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vonbehr.github.io" # the base hostname & protocol for your site

# Logo left of title
logo: "/assets/images/logo_cube.jpg"
masthead_title: "Florian von Behr"

title_separator: "|"
repository: "vonbehr/vonbehr.github.io"

locale: "de-DE"

atom_feed:
  hide: true

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "catppuccin_latte" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  # - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap

# Site Author
author:
  name: ""
  avatar: "/assets/images/florian_von_behr.jpeg"
  # bio: "Building scalable CGI pipelines for high-end visualization."
  # location: "Bremen"
  links:
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/florianvonbehr/"
    - label: "Xing"
      icon: "fa-brands fa-square-xing"
      url: "https://www.xing.com/profile/Florian_vBehr/"
    - label: "Mail"
      icon: "fa-solid fa-envelope"
      url: "mailto:florian@florianvonbehr.de"

# Sidebar
sidebar:
  - title: "Pipeline Entwicklung"
    text: "Ich entwickle Produktionspipelines für moderne CGI-Workflows – von Asset-Management und Workflow-Automatisierung bis zur Integration aktueller Technologien wie USD, MaterialX und Cloud-Rendering."

  - title: "Technical Direction"
    text: "Ich verbinde kreative Teams mit technischer Infrastruktur und entwickle Prozesse, die Produktionen effizienter, robuster und skalierbarer machen."


  - title: "High_end Visualisierung"
    text: "Seit über zwanzig Jahren arbeite ich an Visualisierungen für internationale Kunden aus den Bereichen Automotive, Industrie und Architektur."


# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/florianvonbehr/"
    - label: "Xing"
      icon: "fa-brands fa-square-xing"
      url: "https://www.xing.com/profile/Florian_vBehr/"
    - label: "Mail"
      icon: "fa-solid fa-envelope"
      url: "mailto:florian@florianvonbehr.de"

breadcrumbs: false
search: false
search_full_content: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
